// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdzcwecfouqigaxjecad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkemN3ZWNmb3VxaWdheGplY2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NjI1MjYsImV4cCI6MjA2OTEzODUyNn0.3Rh1Z-vKWx7dtYCxGzpwp12RB0kbkJAa5M_Cw3YUsSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});